<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Symfony\Component\Intl\Countries;

class StatesSeeder extends Seeder
{
    public function run(): void
    {
        $states = [
            [
                'state_name' => 'Afghanistan',
                'capital_city' => 'Kabul',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Australia',
                'capital_city' => 'Canberra',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => 'Ms. Sarah Millard',
                'vote_probability_indonesia' => 'tinggi / moderate / rendah',
                'council_part' => 1,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Bangladesh',
                'capital_city' => 'Dhaka',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Bhutan',
                'capital_city' => 'Thimphu',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Brunei Darussalam',
                'capital_city' => 'Bandar Seri Begawan',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Cambodia',
                'capital_city' => 'Phnom Penh',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'China',
                'capital_city' => 'Beijing',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Xinming Lyu',
                'vote_probability_indonesia' => null,
                'council_part' => 1,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Cook Islands',
                'capital_city' => 'Avarua',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => "Democratic People's Republic of Korea",
                'capital_city' => 'Pyongyang',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Fiji',
                'capital_city' => 'Suva',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'India',
                'capital_city' => 'New Delhi',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Angshumali Rastogi',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Indonesia',
                'capital_city' => 'Jakarta',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Japan',
                'capital_city' => 'Tokyo',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Toshio Yamamoto',
                'vote_probability_indonesia' => null,
                'council_part' => 1,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Kiribati',
                'capital_city' => 'Tarawa',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => "Lao People's Democratic Republic",
                'capital_city' => 'Vientiane',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Malaysia',
                'capital_city' => 'Kuala Lumpur',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Nurulhakeem Hasim',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Maldives',
                'capital_city' => 'Malé',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Marshall Islands',
                'capital_city' => 'Majuro',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Micronesia (Federated States of)',
                'capital_city' => 'Palikir',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Mongolia',
                'capital_city' => 'Ulaanbaatar',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Myanmar',
                'capital_city' => 'Nay Pyi Taw',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Nauru',
                'capital_city' => 'Yaren',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Nepal',
                'capital_city' => 'Kathmandu',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'New Zealand',
                'capital_city' => 'Wellington',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Pakistan',
                'capital_city' => 'Islamabad',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Palau',
                'capital_city' => 'Ngerulmud',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Papua New Guinea',
                'capital_city' => 'Port Moresby',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Philippines',
                'capital_city' => 'Manila',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Republic of Korea',
                'capital_city' => 'Seoul',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Samoa',
                'capital_city' => 'Apia',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Singapore',
                'capital_city' => 'Singapore',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => 'Ms. Eileen Poh',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Solomon Islands',
                'capital_city' => 'Honiara',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Sri Lanka',
                'capital_city' => 'Sri Jayawardenepura Kotte',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Thailand',
                'capital_city' => 'Bangkok',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Timor-Leste',
                'capital_city' => 'Dili',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Tonga',
                'capital_city' => 'Nukuʻalofa',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Tuvalu',
                'capital_city' => 'Funafuti',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Vanuatu',
                'capital_city' => 'Port Vila',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Viet Nam',
                'capital_city' => 'Hanoi',
                'icao_region' => 'APAC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Bahrain',
                'capital_city' => 'Manama',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Egypt',
                'capital_city' => 'Cairo',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => 'Dr. Sameh Ahmed Zaky Elhefny',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Iraq',
                'capital_city' => 'Baghdad',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Jordan',
                'capital_city' => 'Amman',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Kuwait',
                'capital_city' => 'Kuwait City',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Lebanon',
                'capital_city' => 'Beirut',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Libya',
                'capital_city' => 'Tripoli',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Oman',
                'capital_city' => 'Muscat',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Qatar',
                'capital_city' => 'Doha',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Essa Abdulla Al-Malki',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Saudi Arabia',
                'capital_city' => 'Riyadh',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Mohammed Sami S Habib',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Sudan',
                'capital_city' => 'Khartoum',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Syrian Arab Republic',
                'capital_city' => 'Damascus',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'United Arab Emirates',
                'capital_city' => 'Abu Dhabi',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Mohammed Salem',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Yemen',
                'capital_city' => "Sana'a",
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Iran (Islamic Republic of)',
                'capital_city' => 'Tehran',
                'icao_region' => 'MID',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Albania',
                'capital_city' => 'Tirana',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Algeria',
                'capital_city' => 'Algiers',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Andorra',
                'capital_city' => 'Andorra la Vella',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Armenia',
                'capital_city' => 'Yerevan',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Austria',
                'capital_city' => 'Vienna',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Azerbaijan',
                'capital_city' => 'Baku',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Belarus',
                'capital_city' => 'Minsk',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Belgium',
                'capital_city' => 'Brussels',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Bosnia and Herzegovina',
                'capital_city' => 'Sarajevo',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Bulgaria',
                'capital_city' => 'Sofia',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Croatia',
                'capital_city' => 'Zagreb',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Cyprus',
                'capital_city' => 'Nicosia',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Czechia',
                'capital_city' => 'Prague',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Denmark',
                'capital_city' => 'Copenhagen',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Henrik Ellermann',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Estonia',
                'capital_city' => 'Tallinn',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Finland',
                'capital_city' => 'Helsinki',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'France',
                'capital_city' => 'Paris',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => 'Ms. Florence Cormon-Veyssière',
                'vote_probability_indonesia' => null,
                'council_part' => 1,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Georgia',
                'capital_city' => 'Tbilisi',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Germany',
                'capital_city' => 'Berlin',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Heinz Decker',
                'vote_probability_indonesia' => null,
                'council_part' => 1,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Greece',
                'capital_city' => 'Athens',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Hungary',
                'capital_city' => 'Budapest',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Iceland',
                'capital_city' => 'Reykjavík',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Ireland',
                'capital_city' => 'Dublin',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Israel',
                'capital_city' => 'Jerusalem',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Italy',
                'capital_city' => 'Rome',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Sergio Martes',
                'vote_probability_indonesia' => null,
                'council_part' => 1,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Kazakhstan',
                'capital_city' => 'Astana',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Kyrgyzstan',
                'capital_city' => 'Bishkek',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Latvia',
                'capital_city' => 'Riga',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Lithuania',
                'capital_city' => 'Vilnius',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Luxembourg',
                'capital_city' => 'Luxembourg',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Malta',
                'capital_city' => 'Valletta',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Monaco',
                'capital_city' => 'Monaco',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Montenegro',
                'capital_city' => 'Podgorica',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Morocco',
                'capital_city' => 'Rabat',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Salah Chekairi',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Netherlands',
                'capital_city' => 'Amsterdam',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'North Macedonia',
                'capital_city' => 'Skopje',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Norway',
                'capital_city' => 'Oslo',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Poland',
                'capital_city' => 'Warsaw',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Mateusz Baczkowski',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Portugal',
                'capital_city' => 'Lisbon',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Republic of Moldova',
                'capital_city' => 'Chișinău',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Romania',
                'capital_city' => 'Bucharest',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Russian Federation',
                'capital_city' => 'Moscow',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'San Marino',
                'capital_city' => 'San Marino',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Serbia',
                'capital_city' => 'Belgrade',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Slovakia',
                'capital_city' => 'Bratislava',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Slovenia',
                'capital_city' => 'Ljubljana',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Spain',
                'capital_city' => 'Madrid',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Ángel Luis Arias Serrano',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Sweden',
                'capital_city' => 'Stockholm',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Switzerland',
                'capital_city' => 'Bern',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => 'Ms. Helena Hallauer-Hess',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Tajikistan',
                'capital_city' => 'Dushanbe',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Tunisia',
                'capital_city' => 'Tunis',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Türkiye',
                'capital_city' => 'Ankara',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Turkmenistan',
                'capital_city' => 'Ashgabat',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Ukraine',
                'capital_city' => 'Kyiv',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'United Kingdom',
                'capital_city' => 'London',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. William Gatward',
                'vote_probability_indonesia' => null,
                'council_part' => 1,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Uzbekistan',
                'capital_city' => 'Tashkent',
                'icao_region' => 'EUR/NAT',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Angola',
                'capital_city' => 'Luanda',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mrs. Illasandra da Silva',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Botswana',
                'capital_city' => 'Gaborone',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Burundi',
                'capital_city' => 'Gitega',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Comoros',
                'capital_city' => 'Moroni',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Djibouti',
                'capital_city' => 'Djibouti',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Eritrea',
                'capital_city' => 'Asmara',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Eswatini',
                'capital_city' => 'Mbabane',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Ethiopia',
                'capital_city' => 'Addis Ababa',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Kenya',
                'capital_city' => 'Nairobi',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Lesotho',
                'capital_city' => 'Maseru',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Madagascar',
                'capital_city' => 'Antananarivo',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Malawi',
                'capital_city' => 'Lilongwe',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Mauritius',
                'capital_city' => 'Port Louis',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Mozambique',
                'capital_city' => 'Maputo',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Namibia',
                'capital_city' => 'Windhoek',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Rwanda',
                'capital_city' => 'Kigali',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Seychelles',
                'capital_city' => 'Victoria',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Somalia',
                'capital_city' => 'Mogadishu',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'South Africa',
                'capital_city' => 'Pretoria',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Luvuyo Lulama Gqeke',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'South Sudan',
                'capital_city' => 'Juba',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Sudan',
                'capital_city' => 'Khartoum',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Uganda',
                'capital_city' => 'Kampala',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. John Wycliffe Kabbs Twijuke',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'United Republic of Tanzania',
                'capital_city' => 'Dodoma',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Zambia',
                'capital_city' => 'Lusaka',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Zimbabwe',
                'capital_city' => 'Harare',
                'icao_region' => 'ESAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Benin',
                'capital_city' => 'Porto-Novo',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Burkina Faso',
                'capital_city' => 'Ouagadougou',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Cameroon',
                'capital_city' => 'Yaoundé',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Cabo Verde',
                'capital_city' => 'Praia',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Central African Republic',
                'capital_city' => 'Bangui',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Chad',
                'capital_city' => "N'Djamena",
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Congo',
                'capital_city' => 'Brazzaville',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => "Côte d'Ivoire",
                'capital_city' => 'Yamoussoukro',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Equatorial Guinea',
                'capital_city' => 'Malabo',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Estanislao Esono Anguesomo',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Gabon',
                'capital_city' => 'Libreville',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Gambia',
                'capital_city' => 'Banjul',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Ghana',
                'capital_city' => 'Accra',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Guinea',
                'capital_city' => 'Conakry',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Guinea-Bissau',
                'capital_city' => 'Bissau',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Liberia',
                'capital_city' => 'Monrovia',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Mali',
                'capital_city' => 'Bamako',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Sidi Sadio Diallo',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Mauritania',
                'capital_city' => 'Nouakchott',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Niger',
                'capital_city' => 'Niamey',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Nigeria',
                'capital_city' => 'Abuja',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Mahmoud Sani Ben Tukur',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Sao Tome and Principe',
                'capital_city' => 'São Tomé',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Senegal',
                'capital_city' => 'Dakar',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Sierra Leone',
                'capital_city' => 'Freetown',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Togo',
                'capital_city' => 'Lomé',
                'icao_region' => 'WACAF',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Argentina',
                'capital_city' => 'Buenos Aires',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Gerardo E. Bompadre',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Bolivia (Plurinational State of)',
                'capital_city' => 'Sucre',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Brazil',
                'capital_city' => 'Brasília',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Michel Arslanian Neto',
                'vote_probability_indonesia' => null,
                'council_part' => 1,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Chile',
                'capital_city' => 'Santiago',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Colombia',
                'capital_city' => 'Bogotá',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Mauricio Ramírez Koppel',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Ecuador',
                'capital_city' => 'Quito',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Chester David Salazar del Pozo',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Guyana',
                'capital_city' => 'Georgetown',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Paraguay',
                'capital_city' => 'Asunción',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Peru',
                'capital_city' => 'Lima',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Suriname',
                'capital_city' => 'Paramaribo',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Uruguay',
                'capital_city' => 'Montevideo',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Gustavo Álvarez Goyoaga',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Venezuela (Bolivarian Republic of)',
                'capital_city' => 'Caracas',
                'icao_region' => 'SAM',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Antigua and Barbuda',
                'capital_city' => "Saint John's",
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Bahamas',
                'capital_city' => 'Nassau',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Barbados',
                'capital_city' => 'Bridgetown',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Belize',
                'capital_city' => 'Belmopan',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => 'Ms. Anna-Karine Asselin',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Canada',
                'capital_city' => 'Ottawa',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => 'Ms. Anna-Karine Asselin',
                'vote_probability_indonesia' => null,
                'council_part' => 1,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Costa Rica',
                'capital_city' => 'San José',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Cuba',
                'capital_city' => 'Havana',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mrs. Mercedes Vázquez González',
                'vote_probability_indonesia' => null,
                'council_part' => 3,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Dominica',
                'capital_city' => 'Roseau',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Dominican Republic',
                'capital_city' => 'Santo Domingo',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'El Salvador',
                'capital_city' => 'San Salvador',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Grenada',
                'capital_city' => "St. George's",
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Guatemala',
                'capital_city' => 'Guatemala City',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Haiti',
                'capital_city' => 'Port-au-Prince',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Honduras',
                'capital_city' => 'Tegucigalpa',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Jamaica',
                'capital_city' => 'Kingston',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Mexico',
                'capital_city' => 'Mexico City',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => 'Mr. Dionisio Méndez Mayora',
                'vote_probability_indonesia' => null,
                'council_part' => 2,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Nicaragua',
                'capital_city' => 'Managua',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Panama',
                'capital_city' => 'Panama City',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Saint Kitts and Nevis',
                'capital_city' => 'Basseterre',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Saint Lucia',
                'capital_city' => 'Castries',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Saint Vincent and the Grenadines',
                'capital_city' => 'Kingstown',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'Trinidad and Tobago',
                'capital_city' => 'Port of Spain',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => null,
                'dctp_status' => null,
            ],
            [
                'state_name' => 'United States',
                'capital_city' => 'Washington, D.C.',
                'icao_region' => 'NACC',
                'icao_regional_office' => null,
                'rep_in_council' => null,
                'vote_probability_indonesia' => null,
                'council_part' => 1,
                'dctp_status' => null,
            ],
        ];

        $states = array_map(function (array $state) {
            $countryCode = $this->resolveCountryCode($state['state_name']);

            if (! $countryCode) {
                throw new \RuntimeException('Missing country_code mapping for state: '.$state['state_name']);
            }

            $state['country_code'] = $countryCode;

            return $state;
        }, $states);

        DB::table('states')->insert($states);
    }

    private function resolveCountryCode(string $stateName): ?string
    {
        $normalized = $this->normalizeCountryName($stateName);

        foreach (Countries::getNames('en') as $code => $countryName) {
            if ($this->normalizeCountryName($countryName) === $normalized) {
                return strtoupper($code);
            }
        }

        $aliases = [
            'antigua and barbuda' => 'AG',
            'bolivia plurinational state of' => 'BO',
            'bosnia and herzegovina' => 'BA',
            'brunei darussalam' => 'BN',
            'cabo verde' => 'CV',
            'congo' => 'CG',
            'cote d ivoire' => 'CI',
            'democratic people s republic of korea' => 'KP',
            'democratic republic of the congo' => 'CD',
            'iran islamic republic of' => 'IR',
            'lao people s democratic republic' => 'LA',
            'micronesia federated states of' => 'FM',
            'myanmar' => 'MM',
            'north macedonia' => 'MK',
            'republic of korea' => 'KR',
            'republic of moldova' => 'MD',
            'russian federation' => 'RU',
            'saint kitts and nevis' => 'KN',
            'saint lucia' => 'LC',
            'saint vincent and the grenadines' => 'VC',
            'sao tome and principe' => 'ST',
            'syrian arab republic' => 'SY',
            'trinidad and tobago' => 'TT',
            'turkiye' => 'TR',
            'united republic of tanzania' => 'TZ',
            'united states' => 'US',
            'venezuela bolivarian republic of' => 'VE',
            'viet nam' => 'VN',
        ];

        return $aliases[$normalized] ?? null;
    }

    private function normalizeCountryName(string $name): string
    {
        $name = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $name) ?: $name;
        $name = strtolower($name);
        $name = preg_replace('/[^a-z0-9 ]+/', ' ', $name) ?? $name;
        $name = preg_replace('/\s+/', ' ', $name) ?? $name;

        return trim($name);
    }
}
